#ifndef MENUMANAGER_H
#define MENUMANAGER_H

#include "User.h"
#include <string>
#include <vector>
#include <map>

class MenuManager {
private:
    // Menus are always loaded from date- and meal-specific JSON files
    // generated by menu.py into ../data/menus/.
    std::vector<FoodItem> loadMenuFromFile(const std::string& filepath);

public:
    // The filepath parameter is kept for backward compatibility but is unused.
    MenuManager(const std::string& filepath = "./data/menu.json");

    // Get the Nutrislice menu for a given meal type ("breakfast", "lunch", "dinner")
    // and date ("YYYY-MM-DD").
    std::vector<FoodItem> getDailyMenu(const std::string& mealType,
                                       const std::string& date);

    // Simple numbered list display.
    void displayMenu(const std::vector<FoodItem>& menu);

    // Formatted table display with stations and macros.
    void displayMenuTable(const std::vector<FoodItem>& menu);

    // Calculate daily nutrition totals.
    struct DailyTotals {
        int calories;
        double protein;
        double carbs;
        double fats;
    };

    // Meal-plan result returned by MenuManager.
    struct MealPlanResult {
        std::string dateStr;   // "YYYY-MM-DD" for which the plan was generated

        int calorieGoal;
        double proteinGoal;
        double carbsGoal;
        double fatsGoal;

        DailyTotals loggedTotals;  // what the user has already logged for that date

        // Which meals already have any logged food: "breakfast", "lunch", "dinner"
        std::map<std::string, bool> mealLogged;

        // Recommended one item per meal type (only for meals that are not logged).
        // Keys: "breakfast", "lunch", "dinner".
        std::map<std::string, FoodItem> selectedMeals;
    };

    // Generate a meal plan optimized for the user's current day and goals.
    MealPlanResult generateMealPlan(const User& user);

    // Log a meal choice for a user.
    bool logMeal(User& user, const std::string& mealType,
                 const std::string& date, int menuNumber, double servings);

    // Log a specific food item by name (useful for meal plan generation)
    bool logFoodItem(User& user, const std::string& mealType,
                     const std::string& date, const std::string& foodName, double servings);

    // Remove a logged meal for a user.
    bool removeLoggedMeal(User& user, const std::string& date, 
                          const std::string& mealType, const std::string& foodName);

    
    DailyTotals calculateDailyTotals(const User& user, const std::string& date);
};

#endif
