#ifndef MENUMANAGER_H
#define MENUMANAGER_H

#include "User.h"
#include <string>
#include <vector>

class MenuManager {
private:
    // Menus are always loaded from date- and meal-specific JSON files
    // generated by menu.py into ../data/menus/.
    std::vector<FoodItem> loadMenuFromFile(const std::string& filepath);

public:
    // The filepath parameter is kept for backward compatibility but is unused.
    MenuManager(const std::string& filepath = "./data/menu.json");

    // Get the Nutrislice menu for a given meal type ("breakfast", "lunch", "dinner")
    // and date ("YYYY-MM-DD").
    std::vector<FoodItem> getDailyMenu(const std::string& mealType,
                                       const std::string& date);

    // Simple numbered list display.
    void displayMenu(const std::vector<FoodItem>& menu);

    // Formatted table display with stations and macros.
    void displayMenuTable(const std::vector<FoodItem>& menu);

    // Placeholder for future optimization-based meal planning.
    std::vector<FoodItem> generateMealPlan(const User& user);

    // Log a meal choice for a user.
    bool logMeal(User& user, const std::string& mealType,
                 const std::string& date, int menuNumber, double servings);

    // Calculate daily nutrition totals.
    struct DailyTotals {
        int calories;
        double protein;
        double carbs;
        double fats;
    };
    DailyTotals calculateDailyTotals(const User& user, const std::string& date);
};

#endif
